CONTEXT_NAMES = [
    'all_data',
    'ana_end_dt',
    'ana_start_dt',
    'benchmark_series_full',
    'benchmark_series_sliced',
    'cutoff_days',
    'date_option',
    'df_all_instruments',
    'df_all_instruments_full',
    'df_bond',
    'df_bond_full',
    'df_equity',
    'df_equity_full',
    'df_gov_bonds_price',
    'df_gov_bonds_price_full',
    'df_gov_bonds_yield',
    'df_gov_bonds_yield_full',
    'df_index',
    'df_index_full',
    'df_index_vol',
    'df_index_vol_full',
    'df_komoditas',
    'df_komoditas_full',
    'df_mata_uang',
    'df_mata_uang_full',
    'df_suku_bunga',
    'df_suku_bunga_full',
    'end_date_str',
    'full_dfs_dict',
    'get_benchmark_series',
    'latest_dates',
    'latest_update',
    'metrics_all',
    'metrics_bond',
    'metrics_equity',
    'ranked_products_all',
    'ranked_products_bond',
    'ranked_products_equity',
    'risk_free_rate',
    'safe_slice',
    'scoring_mode',
    'selected_bench_label',
    'selected_benchmark_label',
    'selected_benchmark_ticker',
    'start_date_str',
    'weights_dict',
    'young_all',
    'young_bonds',
    'young_equities',
]


def bind_context(ctx):
    return {name: getattr(ctx, name, None) for name in CONTEXT_NAMES}
