[refinitiv]
app_key = "53d0340007f74cb2badfd6aeebd24babb0b1e8b3"
username = "jkharsa@maybank.co.id"

[supabase]
url = "https://bjcidijclqdahimqyusc.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqY2lkaWpjbHFkYWhpbXF5dXNjIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NTA5NTc3NCwiZXhwIjoyMDkwNjcxNzc0fQ.V3_ipd7uTc_iA5UAAR12zucQdUXyr-7X4nLGQ5zOsrg"